# Generated by Django 4.1.1 on 2022-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_name', models.CharField(max_length=40)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('openinghours', models.TextField(default='')),
            ],
        ),
    ]
