# Generated by Django 4.1.1 on 2022-09-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minbwi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofseats', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
