# Generated by Django 4.1.1 on 2022-09-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minbwi_app', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.TextField(default=None),
        ),
    ]
