# Generated by Django 4.1.1 on 2022-09-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minbwi_app', '0006_booking_restaurant_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='numberofseats',
            new_name='number_of_seats',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='openinghours',
            new_name='opening_hours',
        ),
    ]
