# Generated by Django 4.1 on 2022-09-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minbwi_app', '0007_rename_numberofseats_booking_number_of_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
